import { library } from "@fortawesome/fontawesome-svg-core"
import {
  faCalendarAlt,
  faLongArrowAltRight,
  faClock,
  faHourglassHalf,
  faPlus,
  faEye,
  faEyeSlash,
  faUsers,
  faMapMarkerAlt,
  faUser,
  faCog,
  faSignOutAlt,
  faGlobeAmericas,
  faCompass,
  faHistory,
  faAngleDoubleRight,
  faFilter,
  faEdit,
  faTrash,
  faUserMinus,
  faSpinner,
  faSignInAlt,
  faUserPlus,
  faTimes,
  faCheck,
  faMapPin,
  faUserClock,
  faPaperPlane,
  faComments,
  faHiking,
  faBell,
  faMask
} from "@fortawesome/free-solid-svg-icons"

export default (() => {
  library.add(faCalendarAlt)
  library.add(faLongArrowAltRight)
  library.add(faClock)
  library.add(faHourglassHalf)
  library.add(faPlus)
  library.add(faEye)
  library.add(faEyeSlash)
  library.add(faUsers)
  library.add(faMapMarkerAlt)
  library.add(faUser)
  library.add(faCog)
  library.add(faSignInAlt)
  library.add(faSignOutAlt)
  library.add(faGlobeAmericas)
  library.add(faCompass)
  library.add(faHistory)
  library.add(faAngleDoubleRight)
  library.add(faFilter)
  library.add(faEdit)
  library.add(faTrash)
  library.add(faUserMinus)
  library.add(faSpinner)
  library.add(faUserPlus)
  library.add(faTimes)
  library.add(faCheck)
  library.add(faMapPin)
  library.add(faUserClock)
  library.add(faPaperPlane)
  library.add(faComments)
  library.add(faHiking)
  library.add(faBell)
  library.add(faMask)
})()
